### ISSUE TITLE
SCREENSHOT CHALLENGE CTF

### ISSUE THREAD

**Issue by dunnoctf** [QzSG/CTF-Write-Ups#3]
HI!
Can we talk about Screenshot Challenge?

Any e-mail where we can talk?

Cheers

**Comment by QzSG** [comment]
Not the right place to ask, just email the syschron team? They are very helpful

I could suggest searching for things like image forensics, hidding data in images
A hint would be `https://ctfs.github.io/resources/topics/steganography/invisible-text/README.html`
